import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Composite indexes for the most common query patterns:
 *
 *  - Every TraceableEntity table is repeatedly scanned with the predicate
 *    `WHERE businessKey = ? AND isCurrent = 1` (SnapshotService, normaliser
 *    version lookup). The single-column indexes generated by `@Index()`
 *    cover only one column each, forcing a filter step. A composite covers
 *    both, halving the work and stabilising the query plan.
 *
 *  - `(severity, projectId)` on alert helps the Overview page's "critical
 *    count per project" query.
 *
 *  - `(alertId, createdAt)` on decision_review lets us cheaply read the
 *    latest review per decision (the "current state" query).
 */
export class AddIndexes1780487150900 implements MigrationInterface {
  name = 'AddIndexes1780487150900';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const traceableTables = [
      'project',
      'activity',
      'resource',
      'report',
      'resource_assignment',
      'alert',
      'governance_policy',
    ];
    for (const t of traceableTables) {
      // alert + governance_policy don't have `isCurrent`+`businessKey`; skip those.
      if (t === 'alert' || t === 'governance_policy') continue;
      await queryRunner.query(
        `CREATE INDEX \`IDX_${t}_bizkey_current\` ON \`${t}\` (\`businessKey\`, \`isCurrent\`)`,
      );
    }

    await queryRunner.query(
      `CREATE INDEX \`IDX_alert_severity_project\` ON \`alert\` (\`severity\`, \`projectId\`)`,
    );
    await queryRunner.query(
      `CREATE INDEX \`IDX_decision_review_alert_createdAt\` ON \`decision_review\` (\`alertId\`, \`createdAt\`)`,
    );
    await queryRunner.query(
      `CREATE INDEX \`IDX_governance_policy_key_current\` ON \`governance_policy\` (\`projectKey\`, \`isCurrent\`)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const drops = [
      'DROP INDEX `IDX_project_bizkey_current` ON `project`',
      'DROP INDEX `IDX_activity_bizkey_current` ON `activity`',
      'DROP INDEX `IDX_resource_bizkey_current` ON `resource`',
      'DROP INDEX `IDX_report_bizkey_current` ON `report`',
      'DROP INDEX `IDX_resource_assignment_bizkey_current` ON `resource_assignment`',
      'DROP INDEX `IDX_alert_severity_project` ON `alert`',
      'DROP INDEX `IDX_decision_review_alert_createdAt` ON `decision_review`',
      'DROP INDEX `IDX_governance_policy_key_current` ON `governance_policy`',
    ];
    for (const sql of drops) await queryRunner.query(sql);
  }
}
